/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'TemperedGlass' : IDL.Null,
  'PowerBank' : IDL.Null,
  'Handsfree' : IDL.Null,
  'Charger' : IDL.Null,
  'Other' : IDL.Null,
  'Cable' : IDL.Null,
  'Cover' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
  'salePrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'quantity' : IDL.Nat,
  'category' : Category,
  'salePrice' : IDL.Nat,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'date' : IDL.Int,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'profit' : IDL.Nat,
  'salePrice' : IDL.Nat,
});
export const Settings = IDL.Record({
  'pin' : IDL.Text,
  'lockEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSalesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Sale)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'recordSale' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'toggleLock' : IDL.Func([], [], []),
  'updatePin' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'TemperedGlass' : IDL.Null,
    'PowerBank' : IDL.Null,
    'Handsfree' : IDL.Null,
    'Charger' : IDL.Null,
    'Other' : IDL.Null,
    'Cable' : IDL.Null,
    'Cover' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
    'salePrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'quantity' : IDL.Nat,
    'category' : Category,
    'salePrice' : IDL.Nat,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'date' : IDL.Int,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'profit' : IDL.Nat,
    'salePrice' : IDL.Nat,
  });
  const Settings = IDL.Record({ 'pin' : IDL.Text, 'lockEnabled' : IDL.Bool });
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSalesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'recordSale' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'toggleLock' : IDL.Func([], [], []),
    'updatePin' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };