/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'TemperedGlass' : null } |
  { 'PowerBank' : null } |
  { 'Handsfree' : null } |
  { 'Charger' : null } |
  { 'Other' : null } |
  { 'Cable' : null } |
  { 'Cover' : null };
export interface Product {
  'id' : bigint,
  'purchasePrice' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'quantity' : bigint,
  'category' : Category,
  'salePrice' : bigint,
}
export interface ProductInput {
  'purchasePrice' : bigint,
  'name' : string,
  'quantity' : bigint,
  'category' : Category,
  'salePrice' : bigint,
}
export interface Sale {
  'id' : bigint,
  'purchasePrice' : bigint,
  'date' : bigint,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'profit' : bigint,
  'salePrice' : bigint,
}
export interface Settings { 'pin' : string, 'lockEnabled' : boolean }
export interface _SERVICE {
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getSalesByDateRange' : ActorMethod<[bigint, bigint], Array<Sale>>,
  'getSettings' : ActorMethod<[], Settings>,
  'recordSale' : ActorMethod<[bigint, bigint], bigint>,
  'toggleLock' : ActorMethod<[], undefined>,
  'updatePin' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];